(load-theme 'zenburn t)
(set-background-color "black")
(set-face-background 'hl-line "#050555")
(set-cursor-color "#ff4520")
(set-mouse-color "#ffffff")
(menu-bar-mode -1)
(toggle-scroll-bar -1)
(tool-bar-mode -1)
(global-linum-mode 1)
